name: Deploy TODO App
on:  
  push:
    branches:
      - master
jobs:
  deployapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.M2AIR_GITHUB_CICD }}
          script: "cd /home/ubuntu/devops && .deploy-github.sh"
    
